version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: medsu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Uralov2005
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    image: medsu
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medsu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Uralov2005
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
